### PR TITLE
Add  checksum recalculation to the utilities

### PR DESCRIPTION
**Pull request by marcelrv**
Add  checksum recalculation to the utilities to allow recalculation in case NMEA0183 device does not provide it.

Also includes testcases

### CODE REVIEW

**Comment by marcelrv** [comment]
related to issue https://github.com/SignalK/signalk-server-node/issues/1044 and PR https://github.com/SignalK/signalk-server-node/pull/1050

**Review by tkurki — CHANGES_REQUESTED** [review]
Thank you!

While the code works could you consider changing it a bit?
- the checksum calculation code is copypaste from https://github.com/SignalK/nmea0183-utilities/blob/master/index.js#L47-L52 - let's extract `checksum(sentence)` function that both exported functions use
- why would you ever call `checksummedSentence` with the second argument false? I would move the condition to the calling code, making the function easier to understand. it is also very easy in js to forget the second argument, creating code that looks good and runs, "hey, here I'm calling checksummedSentence" but it actually does nothing. I would prefer a function that is more explicit and more straightforward to understand, like `withCalculatedChecksum(sentence)` or `calculateChecksum(sentence)`
- use `let` and `const` instead of `var` in new code

**Comment by tkurki** [comment]
The tests had still var and you don't need to use `done` for synchronous tests, but such small details, so I merged. Thanks!

**Comment by marcelrv** [comment]
thanks... I'm not very much familiar with node / javascript programming, hence I took one of the existing tests as the example code and extended it for this new functionality.

I can make another PR to address the let/var thing, do a search/replace in the test cases (as the other test cases have the same)

**Pull request merged**
